export { Bounds } from './Bounds';
export { Link } from './Link';
export { Copyright } from './Copyright';
export { Person } from './Person';
export { Metadata } from './Metadata';
export { Route } from './Route';
export { Point } from './Point';
export { Track } from './Track';
export { Segment } from './Segment';
